name: gitea

networks:
  gitea:
    external: false

volumes:
  gitea:

services:
  gitea:
    image: gitea/gitea:1.24
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__webhook__ALLOWED_HOST_LIST=webhooks,172.20.0.3
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  webhooks:
    image: wb
    container_name: webhooks
    build: 
      context: ./
    ports:
      - "4000:4000"
    networks:
      - gitea
    volumes:
      - /home/pivan/python-project/test_services:/data
      - ~/.ssh:/root/.ssh